import next from "eslint-config-next/core-web-vitals";

const config = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "node_modules/**",
      "next-env.d.ts",
      // Regenerated by `payload generate:types` / `payload generate:importmap`.
      "src/payload-types.ts",
      "src/app/(payload)/admin/importMap.js",
    ],
  },
  ...next,
];

export default config;
