/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'friend-images': FriendImage;
    'character-images': CharacterImage;
    'project-images': ProjectImage;
    'site-images': SiteImage;
    artists: Artist;
    friends: Friend;
    tags: Tag;
    characters: Character;
    artworks: Artwork;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'friend-images': FriendImagesSelect<false> | FriendImagesSelect<true>;
    'character-images': CharacterImagesSelect<false> | CharacterImagesSelect<true>;
    'project-images': ProjectImagesSelect<false> | ProjectImagesSelect<true>;
    'site-images': SiteImagesSelect<false> | SiteImagesSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    friends: FriendsSelect<false> | FriendsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt?: string | null;
  /**
   * Optional visible caption.
   */
  caption?: string | null;
  /**
   * Generated on upload and used as the `next/image` blur placeholder.
   */
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Featured friend banner beside artwork. Crop is locked to 5:2 (about 680×272). What you select is what appears on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friend-images".
 */
export interface FriendImage {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt?: string | null;
  /**
   * Generated on upload and used as the `next/image` blur placeholder.
   */
  blurDataURL?: string | null;
  source?: {
    key?: string | null;
    width?: number | null;
    height?: number | null;
    mimeType?: string | null;
  };
  crop?: {
    x?: number | null;
    y?: number | null;
    width?: number | null;
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    frame?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Character overview card. Crop is locked to 1:1 (about 1200×1200). What you select is what appears on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-images".
 */
export interface CharacterImage {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt?: string | null;
  /**
   * Generated on upload and used as the `next/image` blur placeholder.
   */
  blurDataURL?: string | null;
  source?: {
    key?: string | null;
    width?: number | null;
    height?: number | null;
    mimeType?: string | null;
  };
  crop?: {
    x?: number | null;
    y?: number | null;
    width?: number | null;
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    frame?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Project cover on /projects. Crop is locked to 16:9 (about 1600×900). What you select is what appears on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-images".
 */
export interface ProjectImage {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt?: string | null;
  /**
   * Generated on upload and used as the `next/image` blur placeholder.
   */
  blurDataURL?: string | null;
  source?: {
    key?: string | null;
    width?: number | null;
    height?: number | null;
    mimeType?: string | null;
  };
  crop?: {
    x?: number | null;
    y?: number | null;
    width?: number | null;
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    frame?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Default social / Open Graph preview. Crop is locked to 1.91:1 (about 1200×630). What you select is what appears on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images".
 */
export interface SiteImage {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt?: string | null;
  /**
   * Generated on upload and used as the `next/image` blur placeholder.
   */
  blurDataURL?: string | null;
  source?: {
    key?: string | null;
    width?: number | null;
    height?: number | null;
    mimeType?: string | null;
  };
  crop?: {
    x?: number | null;
    y?: number | null;
    width?: number | null;
    height?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    frame?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  links?:
    | {
        kind:
          | 'website'
          | 'twitter'
          | 'bluesky'
          | 'instagram'
          | 'furaffinity'
          | 'vgen'
          | 'linktree'
          | 'kofi'
          | 'patreon'
          | 'boosty'
          | 'trello'
          | 'telegram'
          | 'discord'
          | 'email';
        /**
         * Full URL, or a bare address when the kind is Email.
         */
        url: string;
        /**
         * Optional tooltip text, e.g. “private” or “Art Channel”.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friends".
 */
export interface Friend {
  id: number;
  name: string;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  /**
   * Banner beside featured artwork. Upload under Friend images — crop is locked to 5:2 to match the site card (~680×270).
   */
  image?: (number | null) | FriendImage;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        kind:
          | 'website'
          | 'twitter'
          | 'bluesky'
          | 'instagram'
          | 'furaffinity'
          | 'vgen'
          | 'linktree'
          | 'kofi'
          | 'patreon'
          | 'boosty'
          | 'trello'
          | 'telegram'
          | 'discord'
          | 'email';
        /**
         * Full URL, or a bare address when the kind is Email.
         */
        url: string;
        /**
         * Optional tooltip text, e.g. “private” or “Art Channel”.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Shown on chips and facet filters, e.g. “beach”.
   */
  label: string;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  /**
   * e.g. Husky/Shepherd-Mix
   */
  species?: string | null;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  /**
   * Lower sorts first on the /ref overview.
   */
  order?: number | null;
  /**
   * Hero image for the overview card and embeds. Falls back to the first image reference sheet when empty.
   */
  mainArt?: {
    /**
     * Overview / card portrait. Upload under Character images — crop is locked to 1:1 to match the card. Reference sheets stay on Media.
     */
    image?: (number | null) | CharacterImage;
    /**
     * Defaults to the character's name.
     */
    alt?: string | null;
    artist?: (number | null) | Artist;
  };
  sfw?: {
    /**
     * Publishes /ref/<character>/sfw.
     */
    enabled?: boolean | null;
    /**
     * Shown on the profile switcher.
     */
    label?: string | null;
    accentColor?: string | null;
    /**
     * Blurb at the top of this profile's panel.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    sheet?: {
      kind?: ('none' | 'image' | 'wip') | null;
      title?: string | null;
      /**
       * Full reference sheet. Stored in Media without cropping so the original stays intact.
       */
      image?: (number | null) | Media;
      description?: string | null;
      artist?: (number | null) | Artist;
      wip?: {
        badge?: string | null;
        aspect?: ('4/3' | '3/2' | '16/9' | '1/1') | null;
        iconCount?: number | null;
        subtitle?: string | null;
        /**
         * Leave empty to use the built-in pool.
         */
        quotes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Scattered across the backdrop. Empty falls back to the drawing kit.
         */
        icons?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Blended left-to-right across the frame. Empty follows the profile accent.
         */
        gradient?:
          | {
              color: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Milliseconds between quote swaps.
         */
        interval?: number | null;
        /**
         * 0–100 swaps the pacing bar for a determinate one.
         */
        progress?: number | null;
      };
    };
  };
  nsfw?: {
    /**
     * Publishes /ref/<character>/nsfw.
     */
    enabled?: boolean | null;
    /**
     * Shown on the profile switcher.
     */
    label?: string | null;
    accentColor?: string | null;
    /**
     * Blurb at the top of this profile's panel.
     */
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    sheet?: {
      kind?: ('none' | 'image' | 'wip') | null;
      title?: string | null;
      /**
       * Full reference sheet. Stored in Media without cropping so the original stays intact.
       */
      image?: (number | null) | Media;
      description?: string | null;
      artist?: (number | null) | Artist;
      wip?: {
        badge?: string | null;
        aspect?: ('4/3' | '3/2' | '16/9' | '1/1') | null;
        iconCount?: number | null;
        subtitle?: string | null;
        /**
         * Leave empty to use the built-in pool.
         */
        quotes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Scattered across the backdrop. Empty falls back to the drawing kit.
         */
        icons?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Blended left-to-right across the frame. Empty follows the profile accent.
         */
        gradient?:
          | {
              color: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Milliseconds between quote swaps.
         */
        interval?: number | null;
        /**
         * 0–100 swaps the pacing bar for a determinate one.
         */
        progress?: number | null;
      };
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  /**
   * Just the subject. Who else is in the picture belongs in “Also featuring”, not the title.
   */
  title: string;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  character: number | Character;
  profile: 'sfw' | 'nsfw';
  /**
   * In-progress commissions can ship without a final image and show WIP sketches instead.
   */
  lifecycle?: ('complete' | 'in_progress') | null;
  /**
   * Final artwork. Required once the piece is marked complete.
   */
  image?: (number | null) | Media;
  commission?: {
    paid?: boolean | null;
    artistStarted?: boolean | null;
    lastArtistUpdateAt?: string | null;
    lastArtistUpdateNote?: string | null;
  };
  /**
   * Progress sketches. Kept after completion when “Show WIP history” is on.
   */
  wipImages?:
    | {
        image: number | Media;
        caption?: string | null;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What the overview / gallery card shows while in progress.
   */
  overviewDisplay?: ('generated' | 'wipImage') | null;
  /**
   * Should be one of the WIP sketches above.
   */
  overviewWipImage?: (number | null) | Media;
  wipPlaceholder?: {
    badge?: string | null;
    aspect?: ('4/3' | '3/2' | '16/9' | '1/1') | null;
    iconCount?: number | null;
    subtitle?: string | null;
    /**
     * Leave empty to use the built-in pool.
     */
    quotes?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Scattered across the backdrop. Empty falls back to the drawing kit.
     */
    icons?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Blended left-to-right across the frame. Empty follows the profile accent.
     */
    gradient?:
      | {
          color: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Milliseconds between quote swaps.
     */
    interval?: number | null;
    /**
     * 0–100 swaps the pacing bar for a determinate one.
     */
    progress?: number | null;
  };
  /**
   * When the piece is finished, still show the WIP sketches on the public detail page.
   */
  showWipHistory?: boolean | null;
  reminder?: {
    enabled?: boolean | null;
    interval?: number | null;
    unit?: ('days' | 'weeks' | 'months') | null;
    /**
     * Filled automatically when reminders are enabled.
     */
    nextAt?: string | null;
    lastSentAt?: string | null;
  };
  artist?: (number | null) | Artist;
  /**
   * Everyone else in the picture. The character above is always featured.
   */
  featuring?:
    | (
        | {
            relationTo: 'characters';
            value: number | Character;
          }
        | {
            relationTo: 'friends';
            value: number | Friend;
          }
      )[]
    | null;
  tags?: (number | Tag)[] | null;
  /**
   * Lower sorts first within the profile's gallery.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase letters, digits and hyphens only.
   */
  slug: string;
  /**
   * One or two lines, shown on the card and in link previews.
   */
  summary?: string | null;
  /**
   * Card / hero cover. Upload under Project images — crop is locked to 16:9 to match the project cards.
   */
  coverImage?: (number | null) | ProjectImage;
  /**
   * The full write-up, shown on the project's own page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        kind:
          | 'website'
          | 'twitter'
          | 'bluesky'
          | 'instagram'
          | 'furaffinity'
          | 'vgen'
          | 'linktree'
          | 'kofi'
          | 'patreon'
          | 'boosty'
          | 'trello'
          | 'telegram'
          | 'discord'
          | 'email';
        /**
         * Full URL, or a bare address when the kind is Email.
         */
        url: string;
        /**
         * Optional tooltip text, e.g. “private” or “Art Channel”.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('live' | 'wip' | 'planned' | 'archived') | null;
  year?: number | null;
  /**
   * Show on the landing page's work grid.
   */
  featured?: boolean | null;
  /**
   * Lower sorts first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'friend-images';
        value: number | FriendImage;
      } | null)
    | ({
        relationTo: 'character-images';
        value: number | CharacterImage;
      } | null)
    | ({
        relationTo: 'project-images';
        value: number | ProjectImage;
      } | null)
    | ({
        relationTo: 'site-images';
        value: number | SiteImage;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'friends';
        value: number | Friend;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friend-images_select".
 */
export interface FriendImagesSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  source?:
    | T
    | {
        key?: T;
        width?: T;
        height?: T;
        mimeType?: T;
      };
  crop?:
    | T
    | {
        x?: T;
        y?: T;
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        frame?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-images_select".
 */
export interface CharacterImagesSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  source?:
    | T
    | {
        key?: T;
        width?: T;
        height?: T;
        mimeType?: T;
      };
  crop?:
    | T
    | {
        x?: T;
        y?: T;
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        frame?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-images_select".
 */
export interface ProjectImagesSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  source?:
    | T
    | {
        key?: T;
        width?: T;
        height?: T;
        mimeType?: T;
      };
  crop?:
    | T
    | {
        x?: T;
        y?: T;
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        frame?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images_select".
 */
export interface SiteImagesSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  source?:
    | T
    | {
        key?: T;
        width?: T;
        height?: T;
        mimeType?: T;
      };
  crop?:
    | T
    | {
        x?: T;
        y?: T;
        width?: T;
        height?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        frame?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  links?:
    | T
    | {
        kind?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friends_select".
 */
export interface FriendsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  links?:
    | T
    | {
        kind?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  species?: T;
  slug?: T;
  order?: T;
  mainArt?:
    | T
    | {
        image?: T;
        alt?: T;
        artist?: T;
      };
  sfw?:
    | T
    | {
        enabled?: T;
        label?: T;
        accentColor?: T;
        description?: T;
        sheet?:
          | T
          | {
              kind?: T;
              title?: T;
              image?: T;
              description?: T;
              artist?: T;
              wip?:
                | T
                | {
                    badge?: T;
                    aspect?: T;
                    iconCount?: T;
                    subtitle?: T;
                    quotes?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    icons?:
                      | T
                      | {
                          name?: T;
                          id?: T;
                        };
                    gradient?:
                      | T
                      | {
                          color?: T;
                          id?: T;
                        };
                    interval?: T;
                    progress?: T;
                  };
            };
      };
  nsfw?:
    | T
    | {
        enabled?: T;
        label?: T;
        accentColor?: T;
        description?: T;
        sheet?:
          | T
          | {
              kind?: T;
              title?: T;
              image?: T;
              description?: T;
              artist?: T;
              wip?:
                | T
                | {
                    badge?: T;
                    aspect?: T;
                    iconCount?: T;
                    subtitle?: T;
                    quotes?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    icons?:
                      | T
                      | {
                          name?: T;
                          id?: T;
                        };
                    gradient?:
                      | T
                      | {
                          color?: T;
                          id?: T;
                        };
                    interval?: T;
                    progress?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  character?: T;
  profile?: T;
  lifecycle?: T;
  image?: T;
  commission?:
    | T
    | {
        paid?: T;
        artistStarted?: T;
        lastArtistUpdateAt?: T;
        lastArtistUpdateNote?: T;
      };
  wipImages?:
    | T
    | {
        image?: T;
        caption?: T;
        addedAt?: T;
        id?: T;
      };
  overviewDisplay?: T;
  overviewWipImage?: T;
  wipPlaceholder?:
    | T
    | {
        badge?: T;
        aspect?: T;
        iconCount?: T;
        subtitle?: T;
        quotes?:
          | T
          | {
              text?: T;
              id?: T;
            };
        icons?:
          | T
          | {
              name?: T;
              id?: T;
            };
        gradient?:
          | T
          | {
              color?: T;
              id?: T;
            };
        interval?: T;
        progress?: T;
      };
  showWipHistory?: T;
  reminder?:
    | T
    | {
        enabled?: T;
        interval?: T;
        unit?: T;
        nextAt?: T;
        lastSentAt?: T;
      };
  artist?: T;
  featuring?: T;
  tags?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  coverImage?: T;
  body?: T;
  links?:
    | T
    | {
        kind?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  status?: T;
  year?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Serves the maintenance screen to visitors. The admin stays reachable.
   */
  maintenanceMode?: boolean | null;
  maintenanceMessage?: string | null;
  /**
   * Path prefixes that stay reachable during maintenance (exact match or subpaths). Defaults to /ref. Clear the list to put every public route behind the screen.
   */
  maintenanceExcludedPaths?: string[] | null;
  heroTitle?: string | null;
  heroTagline?: string | null;
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Default social preview. Upload under Site images — crop is locked to 1.91:1 (1200×630).
   */
  ogImage?: (number | null) | SiteImage;
  links?:
    | {
        kind:
          | 'website'
          | 'twitter'
          | 'bluesky'
          | 'instagram'
          | 'furaffinity'
          | 'vgen'
          | 'linktree'
          | 'kofi'
          | 'patreon'
          | 'boosty'
          | 'trello'
          | 'telegram'
          | 'discord'
          | 'email';
        /**
         * Full URL, or a bare address when the kind is Email.
         */
        url: string;
        /**
         * Optional tooltip text, e.g. “private” or “Art Channel”.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  notifications?: {
    /**
     * Which channels to use. “Both” tries each configured channel; if ntfy is not configured, SMTP is used as the fallback.
     */
    channel?: ('ntfy' | 'smtp' | 'both') | null;
    ntfy?: {
      /**
       * e.g. https://ntfy.sh
       */
      serverUrl?: string | null;
      topic?: string | null;
      /**
       * Optional access token (secret).
       */
      token?: string | null;
    };
    smtp?: {
      host?: string | null;
      port?: number | null;
      /**
       * Use TLS (typically for port 465).
       */
      secure?: boolean | null;
      user?: string | null;
      /**
       * SMTP password (secret).
       */
      password?: string | null;
      from?: string | null;
      to?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  maintenanceMode?: T;
  maintenanceMessage?: T;
  maintenanceExcludedPaths?: T;
  heroTitle?: T;
  heroTagline?: T;
  about?: T;
  ogImage?: T;
  links?:
    | T
    | {
        kind?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  notifications?:
    | T
    | {
        channel?: T;
        ntfy?:
          | T
          | {
              serverUrl?: T;
              topic?: T;
              token?: T;
            };
        smtp?:
          | T
          | {
              host?: T;
              port?: T;
              secure?: T;
              user?: T;
              password?: T;
              from?: T;
              to?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}